### PR TITLE
Handling T64, DoubleDelta, Gorilla codec

### PR DESCRIPTION
**Pull request by sharadgaur**
https://github.com/AfterShip/clickhouse-sql-parser/issues/84

### CODE REVIEW

**Comment by git-hulk** [comment]
Hi @sharadgaur Thanks for your contribution. Would you mind adding the test SQLs to cover this?

**Comment by sharadgaur** [comment]
sure give me 10 min.

**Comment by sharadgaur** [comment]
> Hi @sharadgaur Thanks for your contribution. Would you mind adding the test SQLs to cover this?

Done

**Review by git-hulk — APPROVED** [review]
LGTM, thanks

**Pull request merged**
