### PR TITLE
Add the support of GRANT PRIVILEGE

### LINKED ISSUE #18: Add the support of GRANT expression
refer: https://github.com/AfterShip/clickhouse-sql-parser/issues/16#issuecomment-1770334406

### PR DESCRIPTION
**Pull request by git-hulk**
This closes #18

### CODE REVIEW

**Comment by git-hulk** [comment]
@Lance726 I don't add enough test sql tests since cannot find more cases, may add more later.

**Comment by Lance726** [comment]
> @Lance726 I don't add enough test sql tests since cannot find more cases, may add more later.

ok~

**Comment by git-hulk** [comment]
@orginux Can have a try if you like.

**Comment by orginux** [comment]
I would suggest adding the `ALL` keyword:
```sql
 GRANT ALL ON *.* TO admin_role WITH GRANT OPTION;
```

**Comment by git-hulk** [comment]
> I would suggest adding the `ALL` keyword:
> 
> ```sql
>  GRANT ALL ON *.* TO admin_role WITH GRANT OPTION;
> ```

Thank you, done in https://github.com/AfterShip/clickhouse-sql-parser/commit/57ca48ccb374d87b663eb90f3b0c2a44d6137728

**Comment by orginux** [comment]
Great, thanks for the quick response and solving.
I found another issue, ClickHouse you can provide GRAND without parameters to have access to all columns in a table, for example:
```sql
GRANT SELECT ON database.table_1 TO table_1_select_role;
GRANT INSERT ON database.table_2 TO table_2_insert_role;
```
but currently, the parser supports only grants with parameters.

**Comment by orginux** [comment]
It should also be possible to submit multiple grants in a single query:
```sql
GRANT SELECT, dictGet ON *.*  TO select_all_role;
```

**Comment by git-hulk** [comment]
@orginux Yes, those are missing keywords in GRANT PRIVILEGE and now have been fixed.

**Pull request merged**
